services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
    image: portafolio-bolsa-app2:latest
    container_name: portafolio-bolsa-app2-con
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - NODE_ENV=production
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - SUPABASE_USER=${SUPABASE_USER}
      - SUPABASE_PASS=${SUPABASE_PASS}
    restart: unless-stopped
