/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState } from 'react';
import { formatCLP } from '../utils';
import { 
  Percent, TrendingUp, Sparkles, Award, PieChart, AlertTriangle
} from 'lucide-react';
import { StockHolding, SectorAllocation } from '../types';

interface ChartsAndAnalyticsProps {
  holdings?: StockHolding[];
  contributedCapital: number;
  totalDividends: number;
  totalTaxRefunds: number;
  annualPerformancePercentage: number;
  setAnnualPerformancePercentage: (val: number) => void;
  holdingsCount: number;
  dailyPnL: number;
  sectorAllocation?: SectorAllocation[];
}

export default function ChartsAndAnalytics({
  holdings = [],
  contributedCapital,
  totalDividends,
  totalTaxRefunds,
  annualPerformancePercentage,
  setAnnualPerformancePercentage,
  holdingsCount,
  dailyPnL,
  sectorAllocation = [],
}: ChartsAndAnalyticsProps) {
  const [projectionYear, setProjectionYear] = useState<number>(30);
  const [annualContribution, setAnnualContribution] = useState<number>(0);
  const [reinvestedDividends, setReinvestedDividends] = useState<number>(0);

  // --- CALCULATIONS FOR PAPER PROFIT AND LOSS ---
  const listHoldings = holdings || [];
  
  // Total capital invertido según la suma de costo de compra de cada holding
  const computedContributed = listHoldings.reduce((sum, h) => sum + (h.shares * h.buyPrice), 0);
  // Valorización actual según precio del mercado
  const computedCurrentValue = listHoldings.reduce((sum, h) => sum + (h.shares * h.currentPrice), 0);
  
  // Pérdidas No Realizadas (Minusvalías en acciones que bajaron de precio)
  const totalLosses = listHoldings.reduce((sum, h) => {
    const diff = h.currentPrice - h.buyPrice;
    if (diff < 0) {
      return sum + (Math.abs(diff) * h.shares);
    }
    return sum;
  }, 0);

  // Ganancias de Capital No Realizadas (Plusvalías en acciones que subieron de precio)
  const totalGains = listHoldings.reduce((sum, h) => {
    const diff = h.currentPrice - h.buyPrice;
    if (diff > 0) {
      return sum + (diff * h.shares);
    }
    return sum;
  }, 0);

  // Rendimiento neto de valorización del portafolio (Plusvalías - Minusvalías)
  const netCapitalGainOrLoss = computedCurrentValue - computedContributed;
  const isNetGain = netCapitalGainOrLoss >= 0;

  const holdingsWithLosses = listHoldings.filter(h => h.currentPrice < h.buyPrice);
  const holdingsWithGains = listHoldings.filter(h => h.currentPrice > h.buyPrice);

  const totalFunds = contributedCapital + totalDividends + totalTaxRefunds;

  // Actual annual yield generated by dividends + tax refunds compared to contributed capital
  const generatedYieldPercent = contributedCapital > 0 
    ? ((totalDividends + totalTaxRefunds) / contributedCapital) * 100 
    : 0;

  // Let's compute compounding projection based on the user-defined annual percentage yield
  const compPercentage = annualPerformancePercentage / 100;
  const totalAnnualInput = annualContribution + reinvestedDividends;

  // Year-by-year breakdown with annual contributions and reinvested dividends
  let runningBalance = contributedCapital;
  const yearlyProjections = Array.from({ length: projectionYear }, (_, i) => {
    const startBal = runningBalance;
    const annualReturn = startBal * compPercentage;
    const endBal = startBal + annualReturn + totalAnnualInput;
    const totalContribSoFar = contributedCapital + totalAnnualInput * (i + 1);
    runningBalance = endBal;
    return { year: i + 1, startBal, annualReturn, endBal, totalContribSoFar };
  });

  const projectedValue = yearlyProjections[projectionYear - 1]?.endBal ?? 0;
  const projectedEarned = projectedValue - yearlyProjections[projectionYear - 1]?.totalContribSoFar;

  // Estimated annual dividend income from current holdings

  // Maximum value for Bar Chart scaling
  const maxBarValue = Math.max(contributedCapital, totalDividends, totalTaxRefunds, totalLosses, totalGains, 1000);

  return (
    <div className="space-y-5">
      {/* Header */}
      <div className="flex items-center space-x-2 text-indigo-600">
        <Award className="w-5 h-5" />
        <h3 className="font-bold text-slate-800 text-sm">Resumen de Rentabilidad y Distribución del Capital</h3>
      </div>

      {/* Data delay notice */}
      <div className="bg-amber-50 border border-amber-200 rounded-lg px-3 py-2 text-[10px] text-amber-700 leading-relaxed">
        Los precios y variaciones mostrados provienen de Yahoo Finance y pueden tener un retraso de hasta 10 minutos respecto a la Bolsa de Santiago. Es posible que los valores no coincidan exactamente con los de tu portafolio de inversión original.
      </div>

      {/* Row 1: Yield % + Donut Chart side by side */}
      <div className="grid grid-cols-1 md:grid-cols-5 gap-5">
        {/* Capital Neto */}
        <div className="bg-white p-5 rounded-xl border border-slate-200 shadow-xs flex flex-col justify-center">
          <span className="text-xs text-slate-400 block">Capital Neto</span>
          <span className="text-2xl font-extrabold font-mono text-slate-900 block mt-1">
            {formatCLP(computedContributed)}
          </span>
          <p className="text-[11px] text-slate-500 leading-relaxed mt-2">
            Total aportado en la compra de acciones.
          </p>
        </div>

        {/* Valorización de Mercado */}
        <div className="bg-white p-5 rounded-xl border border-slate-200 shadow-xs flex flex-col justify-center">
          <span className="text-xs text-slate-400 block">Valorización de Mercado</span>
          <span className="text-2xl font-extrabold font-mono text-indigo-600 block mt-1">
            {formatCLP(computedCurrentValue)}
          </span>
          <p className="text-[11px] text-slate-500 leading-relaxed mt-2">
            Capital neto más ganancias/pérdidas totales.
          </p>
        </div>

        {/* Yield Card */}
        <div className="bg-white p-5 rounded-xl border border-slate-200 shadow-xs flex flex-col justify-center">
          <span className="text-xs text-slate-400 block">Tasa de Dividendos + Devolución Generada</span>
          <span className="text-2xl font-extrabold font-mono text-emerald-600 block mt-1">
            {generatedYieldPercent.toFixed(2)}%
          </span>
          <p className="text-[11px] text-slate-500 leading-relaxed mt-2">
            Rentabilidad pasiva acumulada sobre el capital aportado, incluyendo dividendos cobrados y créditos fiscales de la Operación Renta.
          </p>
        </div>

        {/* Daily P&L */}
        <div className="bg-white p-5 rounded-xl border border-slate-200 shadow-xs flex flex-col justify-center">
          <span className="text-xs text-slate-400 block">Ganancia / Pérdida del Día</span>
          <span className={`text-2xl font-extrabold font-mono block mt-1 ${dailyPnL >= 0 ? 'text-emerald-600' : 'text-rose-600'}`}>
            {dailyPnL >= 0 ? '+' : ''}{formatCLP(dailyPnL)}{' '}
            <span className="text-sm font-semibold">
              ({dailyPnL >= 0 ? '+' : ''}
              {computedCurrentValue > 0 ? ((dailyPnL / (computedCurrentValue - dailyPnL)) * 100).toFixed(2) : '0.00'}%)
            </span>
          </span>
          <p className="text-[11px] text-slate-500 leading-relaxed mt-2">Hoy</p>
        </div>

        {/* Portafolio en Vistazo Rápido */}
        <div className="bg-white p-5 rounded-xl border border-slate-200 shadow-xs">
          <div className="flex items-center justify-between mb-3">
            <h4 className="font-bold text-slate-800 text-xs">Composición Activa del Portafolio</h4>
            <span className="text-[9px] bg-slate-100 text-slate-600 font-mono px-1.5 py-0.5 rounded font-bold">{listHoldings.length} {listHoldings.length === 1 ? 'posición' : 'posiciones'}</span>
          </div>
          <div className="space-y-2">
            {listHoldings.length === 0 ? (
              <p className="text-[11px] text-slate-400 text-center py-4">Agrega acciones en "Mi Portafolio" para ver su composición aquí.</p>
            ) : (
              <>
                {listHoldings.sort((a, b) => (b.shares * b.currentPrice) - (a.shares * a.currentPrice)).slice(0, 3).map(h => {
                  const val = h.shares * h.currentPrice;
                  const cost = h.shares * h.buyPrice;
                  const profit = val - cost;
                  const profitPct = cost > 0 ? (profit / cost) * 100 : 0;
                  const weight = totalFunds > 0 ? (val / totalFunds) * 100 : 0;
                  return (
                    <div key={h.id} className="flex items-center gap-2">
                      <div className={`w-1.5 h-1.5 rounded-full shrink-0 self-start mt-1.5 ${profit >= 0 ? 'bg-emerald-500' : 'bg-rose-500'}`} />
                      <div className="flex-1 min-w-0">
                        <div className="flex justify-between items-baseline">
                          <span className="text-[11px] font-bold text-slate-800">{h.ticker}</span>
                          <span className={`text-[10px] font-mono font-bold ${profit >= 0 ? 'text-emerald-600' : 'text-rose-600'}`}>
                            {profit >= 0 ? '+' : ''}{profitPct.toFixed(1)}%
                          </span>
                        </div>
                        <div className="flex justify-between items-center">
                          <span className="text-[9px] text-slate-400 truncate">{h.name}</span>
                          <span className="text-[9px] text-slate-400 font-mono">{weight.toFixed(1)}%</span>
                        </div>
                        <div className="w-full bg-slate-100 rounded-full h-1 mt-0.5 overflow-hidden">
                          <div className={`h-full rounded-full ${profit >= 0 ? 'bg-teal-500' : 'bg-rose-400'}`} style={{ width: `${Math.min(weight, 100)}%` }} />
                        </div>
                      </div>
                    </div>
                  );
                })}
                {listHoldings.length > 3 && (
                  <div className="text-center text-[9px] text-slate-400 pt-1">+{listHoldings.length - 3} {listHoldings.length - 3 === 1 ? 'posición más' : 'posiciones más'} en Mi Portafolio</div>
                )}
              </>
            )}
          </div>
        </div>
      </div>

      {/* Row 2: Minusvalía / Plusvalía / Balance Neto */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div className="bg-rose-50 border border-rose-100/50 p-4 rounded-xl">
          <span className="text-[10px] text-rose-500 uppercase font-bold tracking-wider block">Minusvalía Total</span>
          <span className="text-lg font-bold text-rose-700 font-mono block mt-0.5">-{formatCLP(totalLosses)} <span className="text-xs font-medium text-rose-500">(-{((totalLosses / (computedContributed || 1)) * 100).toFixed(2)}%)</span></span>
          <span className="text-[10px] text-rose-400 font-medium font-mono">{holdingsWithLosses.length} {holdingsWithLosses.length === 1 ? 'activa' : 'activas'}</span>
        </div>
        <div className="bg-emerald-50 border border-emerald-100/50 p-4 rounded-xl">
          <span className="text-[10px] text-emerald-500 uppercase font-bold tracking-wider block">Plusvalía Total</span>
          <span className="text-lg font-bold text-emerald-700 font-mono block mt-0.5">+{formatCLP(totalGains)} <span className="text-xs font-medium text-emerald-500">(+{((totalGains / (computedContributed || 1)) * 100).toFixed(2)}%)</span></span>
          <span className="text-[10px] text-emerald-400 font-medium font-mono">{holdingsWithGains.length} {holdingsWithGains.length === 1 ? 'activa' : 'activas'}</span>
        </div>
        <div className={`p-4 rounded-xl border ${isNetGain ? 'bg-emerald-50 border-emerald-200' : 'bg-rose-50 border-rose-200'}`}>
          <span className="text-[10px] uppercase font-bold tracking-wider block text-slate-500">Balance Neto</span>
          <div className="flex items-baseline gap-2 mt-0.5">
            <span className={`text-lg font-bold font-mono ${isNetGain ? 'text-emerald-700' : 'text-rose-700'}`}>
              {isNetGain ? '+' : ''}{formatCLP(netCapitalGainOrLoss)}
            </span>
            <span className={`text-xs font-bold font-mono ${isNetGain ? 'text-emerald-600' : 'text-rose-600'}`}>
              ({((netCapitalGainOrLoss / (computedContributed || 1)) * 100).toFixed(2)}%)
            </span>
          </div>
        </div>
      </div>

      {/* Row 3: Bar Chart */}
      <div className="bg-white p-5 rounded-xl border border-slate-200 shadow-xs space-y-3">
        <div>
          <h4 className="font-bold text-slate-800 text-xs">Comparativa de Fondos Adquiridos</h4>
          <p className="text-[10px] text-slate-400">Valores consolidados en CLP</p>
        </div>
        <div className="space-y-2">
          <div>
            <div className="flex justify-between text-[10px] font-medium text-slate-700 mb-0.5">
              <span>Capital Neto</span>
              <span className="font-mono font-bold text-slate-900">{formatCLP(contributedCapital)}</span>
            </div>
            <div className="w-full bg-slate-100 rounded-full h-1.5 overflow-hidden">
              <div className="bg-slate-700 h-full rounded-full transition-all duration-700 ease-out" style={{ width: `${Math.max((contributedCapital / maxBarValue) * 100, 3)}%` }} />
            </div>
          </div>
          <div>
            <div className="flex justify-between text-[10px] font-medium text-teal-800 mb-0.5">
              <span>Dividendos</span>
              <span className="font-mono font-bold text-teal-600">{formatCLP(totalDividends)}</span>
            </div>
            <div className="w-full bg-slate-100 rounded-full h-1.5 overflow-hidden">
              <div className="bg-teal-500 h-full rounded-full transition-all duration-700 ease-out" style={{ width: `${Math.max((totalDividends / maxBarValue) * 100, totalDividends > 0 ? 3 : 0)}%` }} />
            </div>
          </div>
          <div>
            <div className="flex justify-between text-[10px] font-medium text-indigo-800 mb-0.5">
              <span>Impuestos TGR</span>
              <span className="font-mono font-bold text-indigo-600">{formatCLP(totalTaxRefunds)}</span>
            </div>
            <div className="w-full bg-slate-100 rounded-full h-1.5 overflow-hidden">
              <div className="bg-indigo-500 h-full rounded-full transition-all duration-700 ease-out" style={{ width: `${Math.max((totalTaxRefunds / maxBarValue) * 100, totalTaxRefunds > 0 ? 3 : 0)}%` }} />
            </div>
          </div>
          {totalGains > 0 && (
            <div>
              <div className="flex justify-between text-[10px] font-medium text-emerald-800 mb-0.5">
                <span>Plusvalía</span>
                <span className="font-mono font-bold text-emerald-600">+{formatCLP(totalGains)}</span>
              </div>
              <div className="w-full bg-slate-100 rounded-full h-1.5 overflow-hidden">
                <div className="bg-emerald-500 h-full rounded-full transition-all duration-700 ease-out" style={{ width: `${Math.max((totalGains / maxBarValue) * 100, 3)}%` }} />
              </div>
            </div>
          )}
          {totalLosses > 0 && (
            <div>
              <div className="flex justify-between text-[10px] font-medium text-rose-800 mb-0.5">
                <span>Minusvalía</span>
                <span className="font-mono font-bold text-rose-600">-{formatCLP(totalLosses)}</span>
              </div>
              <div className="w-full bg-slate-100 rounded-full h-1.5 overflow-hidden">
                <div className="bg-rose-500 h-full rounded-full transition-all duration-700 ease-out" style={{ width: `${Math.max((totalLosses / maxBarValue) * 100, 3)}%` }} />
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Row 4: Objetivo Anual + Simulación side by side */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
        {/* Objetivo Anual */}
        <div className="bg-white p-5 rounded-xl border border-slate-200 shadow-xs space-y-3">
          <div className="flex justify-between items-center">
            <label className="text-xs font-semibold text-slate-700 flex items-center gap-1">
              <Percent className="w-3.5 h-3.5 text-indigo-500" />
              Rentabilidad Objetivo Anual (%)
            </label>
            <span className="text-xs font-mono font-bold text-indigo-600">{annualPerformancePercentage}% anual</span>
          </div>
          <input type="range" min="0" max="30" step="0.1" value={annualPerformancePercentage}
            onChange={(e) => setAnnualPerformancePercentage(Number(e.target.value))}
            className="w-full accent-indigo-600 h-1.5 bg-slate-100 rounded-lg appearance-none cursor-pointer" />
          <div className="flex justify-between text-[10px] text-slate-400 font-mono">
            <span>0% min</span>
            <span>IPSA Histórico (8-11%)</span>
            <span>30% máx</span>
          </div>

          {/* Annual inputs */}
          <div className="flex gap-3 pt-1 border-t border-slate-100">
            <div className="flex-1">
              <label className="text-[9px] text-slate-400 uppercase tracking-wider block mb-1">Aporte anual (CLP)</label>
              <input type="number" min="0" step="1000" value={annualContribution}
                onChange={(e) => setAnnualContribution(Math.max(0, Number(e.target.value)))}
                className="w-full text-xs font-mono border border-slate-200 rounded-lg px-2 py-1.5 focus:outline-none focus:ring-2 focus:ring-indigo-400" />
            </div>
            <div className="flex-1">
              <label className="text-[9px] text-slate-400 uppercase tracking-wider block mb-1">Dividendo reinvertido anual (CLP)</label>
              <input type="number" min="0" step="1000" value={reinvestedDividends}
                onChange={(e) => setReinvestedDividends(Math.max(0, Number(e.target.value)))}
                className="w-full text-xs font-mono border border-slate-200 rounded-lg px-2 py-1.5 focus:outline-none focus:ring-2 focus:ring-indigo-400" />
            </div>
          </div>
        </div>

        {/* Simulación Interés Compuesto */}
        <div className="bg-indigo-950 text-white rounded-xl p-4 border border-indigo-900 shadow-sm relative overflow-hidden">
          <div className="absolute right-0 top-0 transform translate-x-6 -translate-y-6 text-indigo-900 opacity-20 pointer-events-none">
            <TrendingUp className="w-24 h-24" />
          </div>
          <div className="relative z-10 space-y-2.5">
            <div className="flex items-center space-x-1.5">
              <Sparkles className="w-3.5 h-3.5 text-teal-300" />
              <span className="text-[10px] font-bold text-teal-300 uppercase tracking-wider">Simulación de Interés Compuesto</span>
            </div>
            <div className="space-y-1">
              <div className="flex justify-between text-[11px] text-indigo-100 font-medium">
                <span>Horizonte:</span>
                <span className="font-extrabold text-white font-mono">{projectionYear} Años</span>
              </div>
              <input type="range" min="1" max="30" step="1" value={projectionYear}
                onChange={(e) => setProjectionYear(Number(e.target.value))}
                className="w-full h-1 bg-indigo-900 rounded-lg appearance-none cursor-pointer accent-teal-400" />
            </div>
            <div className="grid grid-cols-2 gap-2 pt-1.5 border-t border-indigo-900">
              <div className="space-y-0.5">
                <span className="text-[9px] uppercase tracking-wider text-indigo-200 block">Total Aportado</span>
                <span className="text-xs font-bold font-mono text-indigo-300">{formatCLP(yearlyProjections[projectionYear - 1]?.totalContribSoFar ?? contributedCapital)}</span>
              </div>
              <div className="space-y-0.5">
                <span className="text-[9px] uppercase tracking-wider text-indigo-200 block">Valor Proyectado</span>
                <span className="text-xs font-bold font-mono text-white">{formatCLP(projectedValue)}</span>
              </div>
            </div>
            <div className="flex justify-between text-[11px] pt-1">
              <span className="text-indigo-200">Ganancia Neta:</span>
              <span className="font-extrabold font-mono text-emerald-400">+{formatCLP(projectedEarned)}</span>
            </div>
            {/* Year-by-year breakdown table */}
            <div className="max-h-44 overflow-y-auto text-[10px] font-mono border border-indigo-800 rounded-lg pt-0.5">
              <table className="w-full">
                <thead className="sticky top-0 bg-indigo-900 text-[9px] text-indigo-300 uppercase tracking-wider">
                  <tr>
                    <th className="text-left px-2 py-1 font-semibold">Año</th>
                    <th className="text-right px-2 py-1 font-semibold">Capital inicio</th>
                    <th className="text-right px-2 py-1 font-semibold">Retorno</th>
                    <th className="text-right px-2 py-1 font-semibold">Capital final</th>
                  </tr>
                </thead>
                <tbody>
                  {yearlyProjections.map((p, idx) => (
                    <tr key={p.year} className={idx % 2 === 0 ? 'bg-indigo-950' : 'bg-indigo-900/30'}>
                      <td className="px-2 py-1 text-indigo-300">Año {p.year}</td>
                      <td className="px-2 py-1 text-right text-indigo-200">{formatCLP(p.startBal)}</td>
                      <td className="px-2 py-1 text-right text-emerald-400 font-bold">+{formatCLP(p.annualReturn)}</td>
                      <td className="px-2 py-1 text-right text-white font-bold">{formatCLP(p.endBal)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>

      {/* Row 5: Análisis de Concentración */}
      {sectorAllocation.length > 0 && (
        <div className="bg-white p-5 rounded-xl border border-slate-200 shadow-xs">
          <div className="flex items-center space-x-2 mb-4">
            <PieChart className="w-4 h-4 text-indigo-500" />
            <h4 className="font-bold text-slate-800 text-xs">Análisis de Concentración</h4>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {/* Donut Chart */}
            <div className="flex items-center justify-center">
              <div className="relative w-40 h-40">
                <svg viewBox="0 0 36 36" className="w-full h-full -rotate-90">
                  {sectorAllocation.map((s, i) => {
                    const colors = ['#6366f1','#14b8a6','#f59e0b','#ef4444','#8b5cf6','#ec4899','#06b6d4','#84cc16','#f97316','#64748b'];
                    const totalPct = sectorAllocation.slice(0, i).reduce((a, x) => a + x.percentage, 0);
                    const circumference = 100;
                    const offset = 100 - totalPct;
                    const length = s.percentage;
                    return (
                      <circle key={s.sector} cx="18" cy="18" r="15.915"
                        fill="none" stroke={colors[i % colors.length]} strokeWidth="3"
                        strokeDasharray={`${length} ${circumference - length}`}
                        strokeDashoffset={offset} />
                    );
                  })}
                  <circle cx="18" cy="18" r="15.915" fill="none" stroke="#e2e8f0" strokeWidth="3"
                    strokeDasharray={`${100 - sectorAllocation.reduce((a, s) => a + s.percentage, 0)} 100`}
                    strokeDashoffset={sectorAllocation.reduce((a, s) => a + s.percentage, 0)} />
                </svg>
                <div className="absolute inset-0 flex items-center justify-center">
                  <div className="text-center">
                    <span className="block text-lg font-extrabold font-mono text-slate-800">{sectorAllocation.length}</span>
                    <span className="block text-[9px] text-slate-400 uppercase tracking-wider">Sectores</span>
                  </div>
                </div>
              </div>
            </div>

            {/* Sector List */}
            <div className="space-y-2.5">
              {sectorAllocation.sort((a, b) => b.percentage - a.percentage).map((s, i) => {
                const colors = ['bg-indigo-500','bg-teal-500','bg-amber-500','bg-rose-500','bg-purple-500','bg-pink-500','bg-cyan-500','bg-lime-500','bg-orange-500','bg-slate-400'];
                const isConcentrated = s.percentage > 30;
                return (
                  <div key={s.sector}>
                    <div className="flex items-center justify-between text-[10px] mb-0.5">
                      <div className="flex items-center gap-1">
                        <span className={`w-2 h-2 rounded-full ${colors[i % colors.length]}`} />
                        <span className="font-semibold text-slate-700">{s.sector}</span>
                        {isConcentrated && (
                          <AlertTriangle className="w-3 h-3 text-amber-500" />
                        )}
                      </div>
                      <span className={`font-mono font-bold ${isConcentrated ? 'text-amber-600' : 'text-slate-600'}`}>
                        {s.percentage.toFixed(1)}%
                      </span>
                    </div>
                    <div className="w-full bg-slate-100 rounded-full h-1.5 overflow-hidden">
                      <div className={`h-full rounded-full transition-all duration-700 ease-out ${isConcentrated ? 'bg-amber-400' : colors[i % colors.length]}`}
                        style={{ width: `${s.percentage}%` }} />
                    </div>
                    <div className="flex justify-between text-[9px] text-slate-400 mt-0.5">
                      <span>{formatCLP(s.value)}</span>
                      <span>{s.count} {s.count === 1 ? 'activo' : 'activos'}</span>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>

          {/* Concentration Alert */}
          {sectorAllocation.some(s => s.percentage > 30) && (
            <div className="mt-4 p-3 bg-amber-50 border border-amber-200 rounded-lg">
              <div className="flex items-start gap-2">
                <AlertTriangle className="w-4 h-4 text-amber-500 shrink-0 mt-0.5" />
                <div>
                  <span className="text-[11px] font-bold text-amber-800 block">Alta concentración detectada</span>
                  <span className="text-[10px] text-amber-700 leading-relaxed block mt-0.5">
                    {sectorAllocation.filter(s => s.percentage > 30).map(s => s.sector).join(', ')} supera el 30% del portafolio. 
                    Considera diversificar para reducir riesgo.
                  </span>
                </div>
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
